# Generated by Django 6.0.2 on 2026-02-22 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='instructions_md',
        ),
        migrations.AddField(
            model_name='lab',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lab',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='labsession',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('finished', 'Finished')], max_length=20),
        ),
        migrations.CreateModel(
            name='LabSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_md', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('theory', 'Theory'), ('task', 'Task'), ('solution', 'Solution')])),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='labs.lab')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
