# Generated by Django 6.0.2 on 2026-02-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_remove_lab_instructions_md_lab_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='order',
        ),
    ]
