# Generated by Django 6.0.2 on 2026-02-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_lab_workflow_and_security_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labsession',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='labsession',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
